export const quickAdminSidebarMenu = [
  {
    type: "link",
    label: "Dashboard",
    path: "/admin/quick-commerce",
    icon: "LayoutDashboard",
  },
  {
    type: "section",
    label: "CORE MANAGEMENT",
    items: [
      {
        type: "link",
        label: "Seller Requests",
        path: "/admin/quick-commerce/seller-requests",
        icon: "ClipboardCheck",
      },
      {
        type: "expandable",
        label: "Categories",
        icon: "FolderTree",
        subItems: [
          { label: "All Categories", path: "/admin/quick-commerce/categories/all" },
          { label: "Header Categories", path: "/admin/quick-commerce/categories/header" },
          { label: "Main Categories", path: "/admin/quick-commerce/categories/main" },
          { label: "Sub-Categories", path: "/admin/quick-commerce/categories/sub" },
        ],
      },
      { type: "link", label: "Products", path: "/admin/quick-commerce/products", icon: "Package" },
      {
        type: "expandable",
        label: "Marketing Tools",
        icon: "Megaphone",
        subItems: [
          { label: "Content Manager", path: "/admin/quick-commerce/marketing/content-manager" },
          { label: "Hero & Categories Per Page", path: "/admin/quick-commerce/marketing/hero-categories" },
          { label: "Send Notifications", path: "/admin/quick-commerce/marketing/notifications" },
          { label: "Coupons & Promos", path: "/admin/quick-commerce/marketing/coupons" },
          { label: "Offer Sections", path: "/admin/quick-commerce/marketing/offers" },
          { label: "Shop by Store", path: "/admin/quick-commerce/sellers/active" },
        ],
      },
      {
        type: "expandable",
        label: "Customer Support",
        icon: "MessageSquare",
        subItems: [
          { label: "Help Tickets", path: "/admin/quick-commerce/support/help-tickets" },
          { label: "Review Content", path: "/admin/quick-commerce/support/review-content" },
        ],
      },
      {
        type: "expandable",
        label: "Sellers",
        icon: "Building2",
        subItems: [
          { label: "Active Sellers", path: "/admin/quick-commerce/sellers/active" },
          { label: "Waiting for Review", path: "/admin/quick-commerce/sellers/pending" },
          { label: "Seller Locations", path: "/admin/quick-commerce/sellers/locations" },
        ],
      },
      {
        type: "expandable",
        label: "Delivery Drivers",
        icon: "Truck",
        subItems: [
          { label: "Active Drivers", path: "/admin/quick-commerce/drivers/active" },
          { label: "Waiting for Review", path: "/admin/quick-commerce/drivers/pending" },
          { label: "Track Drivers", path: "/admin/quick-commerce/drivers/track" },
          { label: "Send Money", path: "/admin/quick-commerce/drivers/send-money" },
        ],
      },
      { type: "link", label: "Wallet", path: "/admin/quick-commerce/finance/wallet", icon: "Wallet" },
      { type: "link", label: "Money Requests", path: "/admin/quick-commerce/finance/money-requests", icon: "CreditCard" },
      { type: "link", label: "Seller Payments", path: "/admin/quick-commerce/finance/seller-payments", icon: "Receipt" },
      { type: "link", label: "Collect Cash", path: "/admin/quick-commerce/finance/collect-cash", icon: "IndianRupee" },
      { type: "link", label: "Customers", path: "/admin/quick-commerce/customers", icon: "Users" },
      { type: "link", label: "FAQs", path: "/admin/quick-commerce/support/faqs", icon: "MessageSquare" },
      {
        type: "expandable",
        label: "Orders",
        icon: "FileText",
        subItems: [
          { label: "All Orders", path: "/admin/quick-commerce/orders/all" },
          { label: "New Orders", path: "/admin/quick-commerce/orders/new" },
          { label: "Being Prepared", path: "/admin/quick-commerce/orders/preparing" },
          { label: "On the Way", path: "/admin/quick-commerce/orders/on-the-way" },
          { label: "Delivered", path: "/admin/quick-commerce/orders/delivered" },
          { label: "Cancelled", path: "/admin/quick-commerce/orders/cancelled" },
          { label: "Returned", path: "/admin/quick-commerce/orders/returned" },
        ],
      },
      { type: "link", label: "Fees & Charges", path: "/admin/quick-commerce/settings/fees", icon: "DollarSign" },
      { type: "link", label: "Settings", path: "/admin/quick-commerce/settings/general", icon: "Settings" },
      { type: "link", label: "My Profile", path: "/admin/quick-commerce/settings/profile", icon: "User" },
      { type: "link", label: "System Settings", path: "/admin/quick-commerce/settings/system", icon: "Database" },
      { type: "link", label: "Vendors", path: "/admin/quick-commerce/vendors", icon: "Building2" },
      { type: "link", label: "Storefront Preview", path: "/quick-commerce/user", icon: "Globe" },
    ],
  },
]
